function [ parameters, states ] = bci_Construct
%bci_Construct publishes the parameters and states your filter wants to 
%   introduce into the system.
%   see: http://www.bci2000.org/mediawiki/index.php/Technical_Reference:Parameter_Definition
%   see: http://www.bci2000.org/mediawiki/index.php/Technical_Reference:State_Definition
    files = dir('vepstim/layouts/screenlayout_*.m');
    LAYOUTTYPES = strrep(strrep({files.name},'.m',''),'screenlayout_','');
    layouts = '';
    for ii=1:length(LAYOUTTYPES)
        layouts = [layouts mat2str(ii) ' ' LAYOUTTYPES{ii}];
        if ii~=length(LAYOUTTYPES), layouts = [layouts ', ']; end
    end
    files = dir('vepstim/stimulations/stimulation_*.m');
    STIMULATIONTYPES = strrep(strrep({files.name},'.m',''),'stimulation_','');
    stimulations = '';
    for ii=1:length(STIMULATIONTYPES)
        stimulations = [stimulations mat2str(ii) ' ' STIMULATIONTYPES{ii}];
        if ii~=length(STIMULATIONTYPES), stimulations = [stimulations ', ']; end
    end

    parameters = { ...
      [ 'VEP-General:Connection%20to%20presentation%20layer string tcpiphost= 127.0.0.1:30000 % % % // Host adress ("host:port")' ] ...
      [ 'VEP-General:Display%20settings string monitorResolution= 1920,1080 % % % // Resolution of the GUI (x,y)' ] ...
      [ 'VEP-General:Display%20settings int monitorRefreshRate= 60 0 0 240 // Monitor refresh rate (in Hz)' ] ...
      [ 'VEP-General:Display%20settings string windowSize= fullscreen % % % // "fullscreen", or [top,left,width,height] in pixels' ] ...
      [ 'VEP-General:Display%20settings int hideCursor= 1 0 0 1 // Hide mouse cursor durin a run (boolean)' ] ...
      [ 'VEP-General:Colors string stimulusColor= 0xFFFFFF 0xFFFFFF % % // Stimulus color (color)' ] ...
      [ 'VEP-General:Colors string highlightColor= 0xFFFF00 0xFFFF00 % % // Target highlight color (color)' ] ...
      [ 'VEP-General:Colors string targetColor= 0x8C8C8C 0x8C8C8C % % // Target label font-color (color)' ] ...
      [ 'VEP-General:Colors string infoColor= 0xFFFF00 0xFFFF00 % % // Info font-color (color)' ] ...
      [ 'VEP-General:Debug int debug= 0 0 0 1 // Show debug messages (boolean)' ] ...
      [ 'VEP-Setup:Layout int layout= 1 1 1 ' mat2str(length(LAYOUTTYPES)) ' // Layout: ' layouts ' (enumeration)' ] ...
      [ 'VEP-Setup:Layout int boxes_x= 8 8 1 20 // Number of columns' ] ...
      [ 'VEP-Setup:Layout int boxes_y= 4 4 1 20 // Number of rows' ] ...
      [ 'VEP-Setup:Layout string target_names= cellstr(%5B%27A%27%3A%27Z%27%2C%27_%27%2C%271%27%3A%275%27%5D%27) % % % // target order to complete during the run (in Matlab format)' ] ...
      [ 'VEP-Setup:Mode%20selection int trainmode= 1 1 1 4 // Run-Mode: 1 Spatial filter training, 2 Adaptive training, 3 Free Mode - No training, 4 Do nothing (enumeration)' ] ...
      [ 'VEP-Setup:Stimulation%20Type int stimulation= 1 1 1 ' mat2str(length(STIMULATIONTYPES)) ' // Stimulation Type: ' stimulations ' (enumeration)' ] ...
      [ 'VEP-Setup:Stimulation%20Type string mseqParams= 2,6,1,1 % % % // Params to generate m-sequence (baseVal,powerVal,shift,whichSeq)' ] ...
      [ 'VEP-Setup:Stimulation%20Type int mseqShift= 2 0 0 1000 // Number of bits the mseq will be shifted for successive targets' ] ...
      [ 'VEP-Setup:Stimulation%20Type int stimSeed= 1 0 0 10000 // The random seed (unused for cVEP)' ] ...
      [ 'VEP-Setup:Stimulation%20Type string sequencePool= % % % % // Path to SequencePool.csv file (only Predefined) (inputfile)' ] ...
      [ 'VEP-Setup:Stimulation%20Type int framesPerStimulus= 1 1 1 10 // Number of frames per stimulus' ] ...
      [ 'VEP-Setup:Stimulation%20Type string ssvepFrequency= 0.5 % % % // SSVEP frequency/frequencies (in Matlab format)' ] ...
      [ 'VEP-Setup:Stimulation%20Type string ssvepPhaseShift= pi/2 % % % // SSVEP phase/phases (in Matlab format)' ] ...
      [ 'VEP-Setup:Stimulation%20Type int ssvepBinary= 0 0 0 1 // binary stimulation if true, else sinusoidal (boolean)' ] ...
      [ 'VEP-Setup:Training int modeltype= 1 1 1 2 // Model Type: 1 Regression, 2 Remote (enumeration)' ] ...
      [ 'VEP-Setup:Training string remotemodel= lucille:50000 % % % // Host adress to remote model ("host:port")' ] ...
      [ 'VEP-Setup:Training int timelag= 250 1 1 1000 // window size (in ms)' ] ...
      [ 'VEP-Setup:Classification int classificationMode= 1 1 1 2 // How to classify: 1 Select correct target, 2 Show bit accuracy (enumeration)' ] ...
      [ 'VEP-Setup:Classification int targetSelection= 1 1 1 3 // How to select targets: 1 Hamming distance, 2 Euclidean distance, 3 Correlation (enumeration)' ] ...
      [ 'VEP-Setup:Trial%20Settings string trials= 1 % % % // target order to complete during the run (in Matlab format)' ] ...
      [ 'VEP-Setup:Trial%20Settings int freeMode= 0 0 0 1 // if true, endless mode, otherwise terminate run after length(targets) (boolean)' ] ...
      [ 'VEP-Setup:Trial%20Settings int startWait= 10 1 1 400 // Seconds till start of first trial' ] ...
      [ 'VEP-Setup:Trial%20Settings float trialTime= 1.5 0 0 100000 // Duration of a trial (in s)' ] ...
      [ 'VEP-Setup:Trial%20Settings float interTrialTime= 0.75 0 0 100000 // Time (in s) between successive trials' ] ...
      [ 'VEP-Setup:Trial%20Settings float afterTrialTime= 0 0 0 0.25 // Time (in ms) of inter-trial time that will be used as trial data' ] ...
      [ 'VEP-Setup:Trial%20Settings%20%28Asynchronous%29 int asynchronous= 0 0 0 1 // true = asynchronous mode, false = synchronous mode (boolean)' ] ...
      [ 'VEP-Setup:Trial%20Settings%20%28Asynchronous%29 float minTrialTime= 0.75 0 0 10000 // Minimum duration of a trial (in ms)' ] ...
      [ 'VEP-Setup:Trial%20Settings%20%28Asynchronous%29 string stopthreshold= 50.0 % % % // Minimal distance difference (in %) between most likely and second most likely target' ] ...
      [ 'VEP-Setup:Trial%20Settings%20%28Asynchronous%29 string pValueThreshold= 3.0e-05 % % % // P-Value threshold of predicted target (using correlation)' ] ...
      };
    % format = Name Length Value ByteLocation BitLocation CRLF
    states = { ...
      'Phase 8 0 0 0' ...
      'Targetclass 8 0 0 0' ...
      'Chosenclass 8 0 0 0' ...
      'ErrPclass 8 0 0 0' ...
    };
    
    system('wmic process where name="cVEPMatlabSignalProcessing.exe" CALL setpriority "realtime"');
end